# pretext: Generate your Data
title: Deep Learning
description: Sharif University of Technology Computer Science Deep Learning course
university: Sharif University of Technology
course: Fall 2025
author: Dr. Hamid Beigy

course_videos: 50+
course_duration: 50
course_lessons: 20
course_resources: 30+
